import { SavedArticle } from "@/env";

export const mockArticles: SavedArticle[] = [
    {
        title: "Sample Article Title #1",
        provider: "The Guardian",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-1",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Mar 28 2025",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-1",
        factual_reporting: "Low",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #2",
        provider: "Reuters",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-2",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Dec 26 2024",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-2",
        factual_reporting: "High",
        bias: "Questionable",
        country: null,
    },
    {
        title: "Sample Article Title #3",
        provider: "The Guardian",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-3",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Aug 08 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-3",
        factual_reporting: "Mixed",
        bias: "Left-Center",
        country: null,
    },
    {
        title: "Sample Article Title #4",
        provider: "The Guardian",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-4",
        image_url: "https://example.com/image1.jpg",
        date: "Fri May 11 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-4",
        factual_reporting: "Mixed",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #5",
        provider: "Fox News",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-5",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Apr 23 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-5",
        factual_reporting: "Very High",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #6",
        provider: "NY Times",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-6",
        image_url: "https://example.com/image1.jpg",
        date: "Fri Sep 11 2024",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-6",
        factual_reporting: "Low",
        bias: "Left-Center",
        country: null,
    },
    {
        title: "Sample Article Title #7",
        provider: "Reuters",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-7",
        image_url: "https://example.com/image1.jpg",
        date: "Fri May 06 2025",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-7",
        factual_reporting: "High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #8",
        provider: "Reuters",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-8",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Dec 18 2024",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-8",
        factual_reporting: "High",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #9",
        provider: "NY Times",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-9",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Oct 23 2024",
        fallbackDate: null,
        summary: ["Investors discuss the volatility of tech stocks in global markets."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-9",
        factual_reporting: "Low",
        bias: "Satire",
        country: null,
    },
    {
        title: "Sample Article Title #10",
        provider: "The Guardian",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-10",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Feb 19 2025",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-10",
        factual_reporting: "Low",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #11",
        provider: "NY Times",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-11",
        image_url: "https://example.com/image1.jpg",
        date: "Fri Sep 29 2024",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-11",
        factual_reporting: "Low",
        bias: "Left",
        country: null,
    },
    {
        title: "Sample Article Title #12",
        provider: "NY Times",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-12",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 21 2025",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-12",
        factual_reporting: "Very High",
        bias: "Pro-Science",
        country: null,
    },
    {
        title: "Sample Article Title #13",
        provider: "AOL",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-13",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Jan 13 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-13",
        factual_reporting: "Mixed",
        bias: "Questionable",
        country: null,
    },
    {
        title: "Sample Article Title #14",
        provider: "Reuters",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-14",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 22 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-14",
        factual_reporting: "Mixed",
        bias: "Satire",
        country: null,
    },
    {
        title: "Sample Article Title #15",
        provider: "The Guardian",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-15",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 22 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-15",
        factual_reporting: "Mixed",
        bias: "Right",
        country: null,
    },
    {
        title: "Sample Article Title #16",
        provider: "AOL",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-16",
        image_url: "https://example.com/image1.jpg",
        date: "Fri Jul 17 2024",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-16",
        factual_reporting: "High",
        bias: "Left-Center",
        country: null,
    },
    {
        title: "Sample Article Title #17",
        provider: "BBC",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-17",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 12 2025",
        fallbackDate: null,
        summary: ["Investors discuss the volatility of tech stocks in global markets."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-17",
        factual_reporting: "High",
        bias: "Right",
        country: null,
    },
    {
        title: "Sample Article Title #18",
        provider: "BBC",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-18",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Jul 20 2024",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-18",
        factual_reporting: "Mixed",
        bias: "Right",
        country: null,
    },
    {
        title: "Sample Article Title #19",
        provider: "AOL",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-19",
        image_url: "https://example.com/image4.jpg",
        date: "Fri May 21 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-19",
        factual_reporting: "High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #20",
        provider: "AOL",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-20",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Jan 19 2025",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-20",
        factual_reporting: "High",
        bias: "Left",
        country: null,
    },
    {
        title: "Sample Article Title #21",
        provider: "BBC",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-21",
        image_url: "https://example.com/image1.jpg",
        date: "Fri Jan 20 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-21",
        factual_reporting: "Mixed",
        bias: "Pro-Science",
        country: null,
    },
    {
        title: "Sample Article Title #22",
        provider: "BBC",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-22",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Jul 31 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-22",
        factual_reporting: "High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #23",
        provider: "Fox News",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-23",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Nov 30 2024",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-23",
        factual_reporting: "Very High",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #24",
        provider: "AOL",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-24",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Aug 02 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-24",
        factual_reporting: "Very High",
        bias: "Right",
        country: null,
    },
    {
        title: "Sample Article Title #25",
        provider: "Reuters",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-25",
        image_url: "https://example.com/image1.jpg",
        date: "Fri Sep 25 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-25",
        factual_reporting: "Very High",
        bias: "Left-Center",
        country: null,
    },
    {
        title: "Sample Article Title #26",
        provider: "Reuters",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-26",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Oct 05 2024",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-26",
        factual_reporting: "Low",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #27",
        provider: "BBC",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-27",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Apr 30 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-27",
        factual_reporting: "High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #28",
        provider: "NY Times",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-28",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Sep 05 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-28",
        factual_reporting: "Very High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #29",
        provider: "The Guardian",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-29",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Nov 02 2024",
        fallbackDate: null,
        summary: ["Investors discuss the volatility of tech stocks in global markets."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-29",
        factual_reporting: "Low",
        bias: "Right",
        country: null,
    },
    {
        title: "Sample Article Title #30",
        provider: "Fox News",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-30",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 26 2025",
        fallbackDate: null,
        summary: ["Investors discuss the volatility of tech stocks in global markets."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-30",
        factual_reporting: "Very High",
        bias: "Left",
        country: null,
    },
    {
        title: "Sample Article Title #31",
        provider: "NY Times",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-31",
        image_url: "https://example.com/image3.jpg",
        date: "Fri Mar 10 2025",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-31",
        factual_reporting: "Very High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #32",
        provider: "The Guardian",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-32",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Jan 23 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-32",
        factual_reporting: "Low",
        bias: "Left",
        country: null,
    },
    {
        title: "Sample Article Title #33",
        provider: "BBC",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-33",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Oct 07 2024",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-33",
        factual_reporting: "Very High",
        bias: "Conspiracy-Pseuodscience",
        country: null,
    },
    {
        title: "Sample Article Title #34",
        provider: "BBC",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-34",
        image_url: "https://example.com/image1.jpg",
        date: "Fri May 28 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-34",
        factual_reporting: "Very High",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #35",
        provider: "Reuters",
        authors: ["John Doe", "Jane Smith"],
        url: "https://www.example.com/article-35",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Aug 29 2024",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-35",
        factual_reporting: "Very High",
        bias: "Conspiracy-Pseuodscience",
        country: null,
    },
    {
        title: "Sample Article Title #36",
        provider: "Fox News",
        authors: ["Aol Staff", "Aniket Verma", "May", "At Pm"],
        url: "https://www.example.com/article-36",
        image_url: "https://example.com/image3.jpg",
        date: "Fri May 09 2025",
        fallbackDate: null,
        summary: ["A new report highlights environmental concerns tied to industrial farming."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-36",
        factual_reporting: "Mixed",
        bias: "Right-Center",
        country: null,
    },
    {
        title: "Sample Article Title #37",
        provider: "Fox News",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-37",
        image_url: "https://example.com/image4.jpg",
        date: "Fri Dec 15 2024",
        fallbackDate: null,
        summary: ["Investors discuss the volatility of tech stocks in global markets."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-37",
        factual_reporting: "Very High",
        bias: "LeastBiased",
        country: null,
    },
    {
        title: "Sample Article Title #38",
        provider: "Fox News",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-38",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Jan 29 2025",
        fallbackDate: null,
        summary: ["Scholars analyze the effectiveness of current education reforms."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-38",
        factual_reporting: "Mixed",
        bias: "Conspiracy-Pseuodscience",
        country: null,
    },
    {
        title: "Sample Article Title #39",
        provider: "BBC",
        authors: ["Alice Walker", "David Brooks"],
        url: "https://www.example.com/article-39",
        image_url: "https://example.com/image2.jpg",
        date: "Fri Sep 23 2024",
        fallbackDate: null,
        summary: ["This article examines the growing influence of cryptocurrency in American politics."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-39",
        factual_reporting: "Mixed",
        bias: "Left",
        country: null,
    },
    {
        title: "Sample Article Title #40",
        provider: "Reuters",
        authors: ["Chris Evans", "Emma Stone", "Tom Hanks"],
        url: "https://www.example.com/article-40",
        image_url: "https://example.com/image4.jpg",
        date: "Fri May 07 2025",
        fallbackDate: null,
        summary: ["Experts debate the economic impact of AI on traditional jobs."],
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        id: "mock-id-40",
        factual_reporting: "Very High",
        bias: "Questionable",
        country: null,
    },
];
